package ee.kivistik.backend.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Entity representing a reservation in the system.
 * Each reservation stores information about the customer,
 * the reserved table, the reservation date and time,
 * and the number of people included in the booking.
 * This entity is mapped to the "reservations" table
 * in the database.
 */
@Entity
@Table(name = "reservations")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ReservationEntity {

    /**
     * Unique identifier of the reservation.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    /**
     * Name of the customer who made the reservation.
     */
    private String name;

    /**
     * Table assigned to this reservation.
     * Many reservations can reference the same table,
     * therefore a Many-to-One relationship is used.
     */
    @ManyToOne
    @JoinColumn(name = "table_id")
    private TableEntity table;

    /**
     * Date of the reservation.
     */
    private LocalDate date;

    /**
     * Time of the reservation.
     */
    private LocalTime time;

    /**
     * Number of people included in the reservation.
     */
    private Integer people;

}